### ISSUE TITLE
Provide more details on how to use 'filter' and 'search' query parameters in fetching bookings

### ISSUE THREAD

**Issue by wise-cheng** [dayschedule/dayschedule-api#5]
I am developing an application using dayschedule's api and from the api [docs](https://dayschedule.com/docs/api#tag/Bookings), it isn't obvious as to how to specify 'filter' and 'search'.  I would like to fetch all bookings with a 'resource_id', an example will be  `{{BASE_URL}}/bookings?apiKey={{API_KEY}}&resource_id=<resource_id>`, but it seems that I would need to specific `{{BASE_URL}}/bookings?apiKey={{API_KEY}}&filter=<resource_id>` or similar.

Please clarify how to use 'filter' and 'search', and what fields are supported.  Thanks!

**Comment by vickyRathee** [comment]
@wise-cheng the `resource_id` filter is available now, please try again.

If you are using the SDK - 

```
const data = await ds.bookings.list({resource_id: ID_HERE)

```

If fetching bookings via API endpoint, your example is correct and it should work now - 
```
{{BASE_URL}}/bookings?apiKey={{API_KEY}}&resource_id=<resource_id>
```

Here are the [API specs](https://dayschedule.com/docs/api#tag/Bookings)

![image](https://github.com/dayschedule/dayschedule-api/assets/6106479/936d9602-d734-4b33-8951-969fcb9a5e57)

**Comment by wise-cheng** [comment]
Thanks, works well.

**Comment by wise-cheng** [comment]
Is there further details on how to use the `filter` and `search` params? One use case is to filter by status, i.e. fetch all 'confirmed' bookings belong to a specific `resource_id`.
