### ISSUE TITLE
Add 'invitees' into response on fetching bookings

### ISSUE THREAD

**Issue by wise-cheng** [dayschedule/dayschedule-api#6]
Currently the response from `/bookings?resource_id=<resource_id>` does not include the `invitees` field.  As a work around, I have to call `/bookings/<booking_id>` on each booking to get the invitees information.  The reason I need the invitees information is so that I can customize the rendering of bookings in my app, and currently the invitee's name is only in the 'subject' text in `/bookings?resource_id=<resource_id>` response.

**Comment by vickyRathee** [comment]
There can be thousands of invitees in group event, webinar etc. on a single booking. So there is separate API to fetch invitees by booking id as per the database design.

Use `/invitees?booking_id={booking_id}` API to fetch all the invitees associated with a booking.

https://dayschedule.com/docs/api#tag/Invitees/operation/InviteeController_getInviteesByBookingId
