### ISSUE TITLE
Book an appointment on mobile browsers with the inline popup widget seems to hang after clicking on the 'Confirm booking' button

### ISSUE THREAD

**Issue by wise-cheng** [dayschedule/dayschedule-api#7]
I added an inline popup in a web page for a service resource, and it works fine if the site visitor books an appointment from a desktop browser (Chrome,Safari or Firefox).  However it seems to hang after clicking on the 'Confirm booking' on a mobile browser as it just shows a spinner (mobile Chrome, Safari).  To see the issue, on a mobile browser, go to  https://sohairdesign.lumosworks.com and click on the 'Book An Appointment' link.  See picture below:
![Screenshot 2023-12-04 at 9 21 24 AM](https://github.com/dayschedule/dayschedule-api/assets/103758790/234a1a79-6a35-41df-b188-dc569dfdc155)
>
<img width="551" alt="Screenshot 2023-12-04 at 9 24 15 AM" src="https://github.com/dayschedule/dayschedule-api/assets/103758790/a61426e5-a895-439b-bfc3-00021f789d0e">

P.S. The button now says 'Confirm booking' if no payment gateway is setup. Yay.

**Comment by vickyRathee** [comment]
this is fixed now.
